// src/services/rules.js
//
// The complete rule book Foundry uses to score listings.
// Exposed publicly at GET /v1/rules so builders can learn what the linter checks.

export const RULES = [
  // ─── Identity ────────────────────────────────────────────────────────
  {
    id: 'NAME_EMPTY',
    category: 'identity',
    severity: 'block',
    title: 'Name is required',
    description: 'The identity name field cannot be empty.',
    example_pass: 'Foundry',
    example_fail: '(empty string)',
  },
  {
    id: 'NAME_LENGTH',
    category: 'identity',
    severity: 'block',
    title: 'Name length 3–25 chars (EN) or 2–12 (CJK)',
    description: 'OKX requires brand names within these bounds.',
    example_pass: 'Foundry',
    example_fail: 'F',
  },
  {
    id: 'NAME_TEST_MARKER',
    category: 'identity',
    severity: 'block',
    title: 'No "test/demo/sample" in name',
    description: 'OKX rejects listings that look like sandbox experiments.',
    example_pass: 'Foundry ASP',
    example_fail: 'MyTestAgent',
  },
  {
    id: 'NAME_CELEBRITY',
    category: 'identity',
    severity: 'block',
    title: 'No celebrity / public-figure names',
    description: 'Even substrings (Trump, Musk, CZ, Vitalik) are rejected.',
    example_pass: 'Foundry',
    example_fail: 'TrumpTradeBot',
  },
  {
    id: 'DESC_EMPTY',
    category: 'identity',
    severity: 'block',
    title: 'Description is required',
    description: 'The identity description field cannot be empty.',
    example_pass: 'A clear one-line summary.',
    example_fail: '(empty string)',
  },
  {
    id: 'DESC_SHORT',
    category: 'identity',
    severity: 'block',
    title: 'Description too short (< 30 chars)',
    description: 'OKX wants enough context to understand the agent at a glance.',
    example_pass: 'A 50+ char description explaining what and for whom.',
    example_fail: 'short',
  },
  {
    id: 'DESC_LONG',
    category: 'identity',
    severity: 'block',
    title: 'Description too long (> 500 chars)',
    description: 'Trim to the most important sentence.',
    example_pass: 'Under 500 chars.',
    example_fail: 'More than 500 characters of marketing fluff.',
  },
  {
    id: 'DESC_LENGTH',
    category: 'identity',
    severity: 'block',
    title: 'Description 30–500 chars',
    description: 'The one-line summary of what your agent does and who it\'s for.',
    example_pass: 'Pre-flight to post-flight for OKX.AI Agent Service Providers. Validates, prices, lints, and bootstraps trust.',
    example_fail: 'short',
  },

  // ─── Service ─────────────────────────────────────────────────────────
  {
    id: 'SVC_NAME_EMPTY',
    category: 'service',
    severity: 'block',
    title: 'Service name is required',
    description: 'Each service must have a name.',
    example_pass: 'Lint Listing',
    example_fail: '(empty string)',
  },
  {
    id: 'SVC_NAME_LENGTH',
    category: 'service',
    severity: 'block',
    title: 'Service name 5–30 chars, noun phrase',
    description: 'A short noun phrase describing the service — not a sentence.',
    example_pass: 'Validate Idea',
    example_fail: 'V',
  },
  {
    id: 'SVC_NAME_PRICE',
    category: 'service',
    severity: 'block',
    title: 'No price in service name',
    description: 'The fee is a separate field. Don\'t put "$0.01 USDT" in the name.',
    example_pass: 'Lint Listing',
    example_fail: 'Lint at 0.05 USDT',
  },
  {
    id: 'SVC_DESC_EMPTY',
    category: 'service',
    severity: 'block',
    title: 'Service description is required',
    description: 'Each service needs a 2-part description.',
    example_pass: '① Does the thing.\n② User must provide: 1. input',
    example_fail: '(empty string)',
  },
  {
    id: 'SVC_DESC_LONG',
    category: 'service',
    severity: 'block',
    title: 'Service description too long (> 400 chars)',
    description: 'OKX caps service descriptions at 400 chars.',
    example_pass: 'Under 400 chars.',
    example_fail: 'A 500-character wall of text.',
  },
  {
    id: 'SVC_DESC_TWO_PART',
    category: 'service',
    severity: 'warn',
    title: 'Two-part description (capability + what user provides)',
    description: 'OKX wants: (1) what it does + audience, (2) what the user must provide.',
    example_pass: '① Lints your listing against 19 OKX review rules.\n② User must provide: 1. listing JSON',
    example_fail: 'just a description',
  },
  {
    id: 'SVC_DESC_NO_INPUT_SPEC',
    category: 'service',
    severity: 'warn',
    title: 'Missing the "what the user must provide" half',
    description: 'The 2-part description needs both halves. Add a second line listing the inputs.',
    example_pass: '① Lints listings.\n② User must provide: 1. listing',
    example_fail: '① Lints listings.',
  },
  {
    id: 'SVC_DESC_LINKS',
    category: 'service',
    severity: 'block',
    title: 'No GitHub / Twitter / wallet links in description',
    description: 'OKX policy disallows external links inside service descriptions.',
    example_pass: '① Does the thing.\n② User must provide: 1. input',
    example_fail: 'See https://github.com/x/y',
  },
  {
    id: 'SVC_FEE_HAS_SYMBOL',
    category: 'service',
    severity: 'block',
    title: 'Fee is a plain number (no USDT/USD/$ symbols)',
    description: 'OKX defaults to USDT. Pass a quoted string like "0.01".',
    example_pass: '"fee": "0.01"',
    example_fail: '"fee": "0.01 USDT"',
  },
  {
    id: 'SVC_FEE_REQUIRED',
    category: 'service',
    severity: 'block',
    title: 'API service requires a fee',
    description: 'A2MCP services must have a numeric fee (use "0" if you want to be free).',
    example_pass: '"fee": "0.01"',
    example_fail: '"fee": ""',
  },
  {
    id: 'SVC_TYPE_INVALID',
    category: 'service',
    severity: 'block',
    title: 'Type is A2MCP or A2A',
    description: 'A2MCP = paid API service. A2A = agent-to-agent task.',
    example_pass: '"type": "A2MCP"',
    example_fail: '"type": "WRONG"',
  },
  {
    id: 'SVC_ENDPOINT_REQUIRED',
    category: 'service',
    severity: 'block',
    title: 'A2MCP service requires an https endpoint',
    description: 'Each A2MCP service must have a public https URL.',
    example_pass: '"endpoint": "https://api.example.com/v1"',
    example_fail: '(no endpoint field)',
  },
  {
    id: 'SVC_ENDPOINT_NOT_HTTPS',
    category: 'service',
    severity: 'block',
    title: 'Endpoint is https:// (not http://)',
    description: 'OKX only accepts public https endpoints.',
    example_pass: 'https://api.example.com/v1',
    example_fail: 'http://api.example.com/v1',
  },
  {
    id: 'SVC_ENDPOINT_PRIVATE',
    category: 'service',
    severity: 'block',
    title: 'No localhost / private IPs / .local / .internal',
    description: 'Endpoint must be publicly reachable from the internet.',
    example_pass: 'https://my-asp.onrender.com/v1',
    example_fail: 'http://localhost:3000/api',
  },
  {
    id: 'SVC_ENDPOINT_TOO_LONG',
    category: 'service',
    severity: 'block',
    title: 'Endpoint ≤ 512 chars',
    description: 'URL length cap for storage.',
    example_pass: 'https://my-asp.com/v1',
    example_fail: 'a 600+ char URL',
  },
  {
    id: 'SVC_ENDPOINT_SUSPICIOUS_HOST',
    category: 'service',
    severity: 'warn',
    title: 'Avoid vercel.app / netlify.app / herokuapp.com',
    description: 'These free domains are often rejected by OKX reviewers.',
    example_pass: 'https://my-asp.onrender.com/v1',
    example_fail: 'https://my-asp.vercel.app/v1',
  },

  // ─── Category ────────────────────────────────────────────────────────
  {
    id: 'CATEGORY_MISSING',
    category: 'category',
    severity: 'block',
    title: 'Category is required',
    description: 'Pick the category that best matches your agent\'s primary use case.',
    example_pass: '"category": "FINANCE"',
    example_fail: '(no category field)',
  },
  {
    id: 'CATEGORY_INVALID',
    category: 'category',
    severity: 'block',
    title: 'Category is one of OKX\'s 7 official categories',
    description: 'FINANCE / SOFTWARE_SERVICES / LIFESTYLE / ART_CREATION / EDUCATION / PRODUCTIVITY / SOCIAL',
    example_pass: 'SOFTWARE_SERVICES',
    example_fail: 'CRYPTO',
  },

  // ─── Trust / Disclosure ──────────────────────────────────────────────
  {
    id: 'SVC_DESC_DISCLAIMER',
    category: 'trust',
    severity: 'warn',
    title: 'Avoid legal disclaimers in service description',
    description: 'Move "not financial advice" / "DYOR" to a separate terms field.',
    example_pass: '① Provides price data.\n② User must provide: 1. token symbol',
    example_fail: 'Not financial advice. Do your own research.',
  },
  {
    id: 'SVC_DESC_WALLET_ADDR',
    category: 'trust',
    severity: 'warn',
    title: 'Avoid mentioning wallet/contract addresses in description',
    description: 'Address handling should be a separate input field, not the description.',
    example_pass: '① Pays out to a configured address.\n② User must provide: 1. recipient',
    example_fail: 'Sends 0x1234... to your wallet address',
  },
];

export const RULE_BY_ID = Object.fromEntries(RULES.map((r) => [r.id, r]));

export const RULE_CATEGORIES = ['identity', 'service', 'category', 'trust'];
